ALTER TABLE submissions ADD COLUMN IF NOT EXISTS download_count INT DEFAULT 0;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS rating_sum FLOAT DEFAULT 0;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS rating_count INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
